#Ahora aprenderemos a cargar el programa .ui
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_DoubleSpinBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit, QDoubleSpinBox


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(603, 299)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Form)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_price = QtWidgets.QLineEdit(Form)
        self.lineEdit_price.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_price.setObjectName("lineEdit_price")
        self.horizontalLayout.addWidget(self.lineEdit_price)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(Form)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.horizontalLayout.addWidget(self.doubleSpinBox)
        self.lineEdit_result = QtWidgets.QLineEdit(Form)
        self.lineEdit_result.setStyleSheet("font: 12pt \"MS Shell Dlg 2\";")
        self.lineEdit_result.setObjectName("lineEdit_result")
        self.horizontalLayout.addWidget(self.lineEdit_result)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # Here wqe go!!
        self.doubleSpinBox.valueChanged.connect(self.spin_selected)

    def spin_selected(self):
        if self.lineEdit_price.text() != 0:

            price = float(self.lineEdit_price.text())
            totalPrice = self.doubleSpinBox.value() * price

            self.lineEdit_result.setText(str(totalPrice))



    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Sugar price:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

