# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_CheckBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 123, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_result = QtWidgets.QLabel(Dialog)
        self.label_result.setGeometry(QtCore.QRect(40, 220, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_result.setFont(font)
        self.label_result.setObjectName("label_result")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(200, 90, 148, 83))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_queso = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_queso.setFont(font)
        self.checkBox_queso.setObjectName("checkBox_queso")

        self.checkBox_queso.stateChanged.connect(self.Estra_selected)

        self.verticalLayout.addWidget(self.checkBox_queso)
        self.checkBox_pimi = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_pimi.setFont(font)
        self.checkBox_pimi.setObjectName("checkBox_pimi")

        self.checkBox_pimi.stateChanged.connect(self.Estra_selected)

        self.verticalLayout.addWidget(self.checkBox_pimi)
        self.checkBox_ace = QtWidgets.QCheckBox(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.checkBox_ace.setFont(font)
        self.checkBox_ace.setObjectName("checkBox_ace")

        self.checkBox_ace.stateChanged.connect(self.Estra_selected)

        self.verticalLayout.addWidget(self.checkBox_ace)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)


    def Estra_selected(self):
        cost = 10

        if self.checkBox_queso.isChecked():
            cost = round(cost + 1.96, 2)

        if self.checkBox_pimi.isChecked():
            cost = round(cost + 1.83, 2)

        if self.checkBox_ace.isChecked():
            cost = round(cost + 1.53, 2)

        self.label_result.setText(f'El precio total es: {cost}€')


    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Pizza Hawaiana 10€"))
        self.label_2.setText(_translate("Dialog", "Add Extra:"))
        self.label_result.setText(_translate("Dialog", ""))
        self.checkBox_queso.setText(_translate("Dialog", "Extra Queso 1.96"))
        self.checkBox_pimi.setText(_translate("Dialog", "Pimiento 1.83"))
        self.checkBox_ace.setText(_translate("Dialog", "aceitunas 1.53"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
