# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_LCDNumber_random.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
# importamos randint
from random import randint

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 162)
        Dialog.setStyleSheet("QDialog{\n"
"\n"
"background-color:pink\n"
"\n"
"}")
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lcdNumber = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber.setStyleSheet("QLCDNumber{\n"
"\n"
"background-color:yellow\n"
"\n"
"}")
        self.lcdNumber.setObjectName("lcdNumber")
        self.verticalLayout.addWidget(self.lcdNumber)
        self.btn_number = QtWidgets.QPushButton(Dialog)

        # Signal connect
        self.btn_number.clicked.connect(self.random_generator)


        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_number.setFont(font)
        self.btn_number.setStyleSheet("QPushButton{\n"
"\n"
"background-color:red\n"
"\n"
"}")
        self.btn_number.setObjectName("btn_number")
        self.verticalLayout.addWidget(self.btn_number)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_number.setText(_translate("Dialog", "Push to Random Number"))


    def random_generator(self):
        # cramos un numero random entre 1 y 500
        random = randint(1, 500)
        # ahora lo pasamos al lcdnumber
        self.lcdNumber.display(random)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
