# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_Radio_Button.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog


class Ui_Dialog(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setStyleSheet("QDialog{\n"
"\n"
"background-color: yellow\n"
"\n"
"\n"
"}")
        self.radio_btn_first = QtWidgets.QRadioButton(Dialog)
        self.radio_btn_first.setGeometry(QtCore.QRect(50, 80, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radio_btn_first.setFont(font)
        self.radio_btn_first.setObjectName("radio_btn_first")

        self.radio_btn_first.toggled.connect(self.radio_btn_selected)

        self.radio_btn_business = QtWidgets.QRadioButton(Dialog)
        self.radio_btn_business.setGeometry(QtCore.QRect(50, 120, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radio_btn_business.setFont(font)
        self.radio_btn_business.setObjectName("radio_btn_business")

        self.radio_btn_business.toggled.connect(self.radio_btn_selected)

        self.radio_btn_eco = QtWidgets.QRadioButton(Dialog)
        self.radio_btn_eco.setGeometry(QtCore.QRect(50, 160, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.radio_btn_eco.setFont(font)
        self.radio_btn_eco.setObjectName("radio_btn_eco")

        self.radio_btn_eco.toggled.connect(self.radio_btn_selected)

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 231, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel {\n"
"\n"
"color:green\n"
"\n"
"}")
        self.label.setObjectName("label")
        self.label_resultado = QtWidgets.QLabel(Dialog)
        self.label_resultado.setGeometry(QtCore.QRect(30, 210, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_resultado.setFont(font)
        self.label_resultado.setStyleSheet("Qlabel {\n"
"\n"
"background-color:pink\n"
"\n"
"}")
        self.label_resultado.setText("")
        self.label_resultado.setObjectName("label_resultado")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        


    def radio_btn_selected(self):
        radio_btn = self.sender()
        if radio_btn.isChecked():
            self.label_resultado.setText(f'You are selected: {radio_btn.text()}')




    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.radio_btn_first.setText(_translate("Dialog", "First Class"))
        self.radio_btn_business.setText(_translate("Dialog", "Business Class"))
        self.radio_btn_eco.setText(_translate("Dialog", "Eco Class"))
        self.label.setText(_translate("Dialog", "Select your type flight:"))




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
