# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt_Radio_Button_II.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 418)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 190, 221, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_result = QtWidgets.QLabel(Dialog)
        self.label_result.setGeometry(QtCore.QRect(20, 360, 561, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_result.setFont(font)
        self.label_result.setText("")
        self.label_result.setObjectName("label_result")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(40, 70, 89, 83))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radiobtn_py = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radiobtn_py.setFont(font)
        self.radiobtn_py.setObjectName("radiobtn_py")

        self.radiobtn_py.toggled.connect(self.Radio_selected)

        self.verticalLayout.addWidget(self.radiobtn_py)
        self.radiobtn_java = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radiobtn_java.setFont(font)
        self.radiobtn_java.setObjectName("radiobtn_java")

        self.radiobtn_java.toggled.connect(self.Radio_selected)

        self.verticalLayout.addWidget(self.radiobtn_java)
        self.radiobtn_js = QtWidgets.QRadioButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radiobtn_js.setFont(font)
        self.radiobtn_js.setObjectName("radiobtn_js")

        self.radiobtn_js.toggled.connect(self.Radio_selected)

        self.verticalLayout.addWidget(self.radiobtn_js)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(40, 250, 105, 83))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radiobtn_cash = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radiobtn_cash.setFont(font)
        self.radiobtn_cash.setObjectName("radiobtn_cash")

        self.radiobtn_cash.toggled.connect(self.Radio_selected)

        self.verticalLayout_2.addWidget(self.radiobtn_cash)
        self.radiobtn_paypal = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radiobtn_paypal.setFont(font)
        self.radiobtn_paypal.setObjectName("radiobtn_paypal")

        self.radiobtn_paypal.toggled.connect(self.Radio_selected)

        self.verticalLayout_2.addWidget(self.radiobtn_paypal)
        self.radiobtn_card = QtWidgets.QRadioButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.radiobtn_card.setFont(font)
        self.radiobtn_card.setObjectName("radiobtn_card")

        self.radiobtn_card.toggled.connect(self.Radio_selected)

        self.verticalLayout_2.addWidget(self.radiobtn_card)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Elige tu Libro:"))
        self.label_2.setText(_translate("Dialog", "Elige tu método de pago:"))
        self.radiobtn_py.setText(_translate("Dialog", "Python"))
        self.radiobtn_java.setText(_translate("Dialog", "Java"))
        self.radiobtn_js.setText(_translate("Dialog", "JavaSript"))
        self.radiobtn_cash.setText(_translate("Dialog", "Cash"))
        self.radiobtn_paypal.setText(_translate("Dialog", "Paypal"))
        self.radiobtn_card.setText(_translate("Dialog", "Credit Card"))


    def Radio_selected(self):
        select_1 = ''
        select_2 = ''

        if self.radiobtn_py.isChecked()== True:
            select_1 = 'Python'
            self.label_result.setText(f" libro seleccionado: {select_1}   Pago seleccionado: {select_2}")

        if self.radiobtn_js.isChecked()== True:
            select_1 = 'JavaScript'
            self.label_result.setText(f" libro seleccionado: {select_1}   Pago seleccionado: {select_2}")

        if self.radiobtn_java.isChecked()== True:
            select_1 = 'Java'
            self.label_result.setText(f" libro seleccionado: {select_1}   Pago seleccionado: {select_2}")

        if self.radiobtn_cash.isChecked()== True:
            select_2 = 'Cash'
            self.label_result.setText(f" libro seleccionado: {select_1}   Pago seleccionado: {select_2}")

        if self.radiobtn_paypal.isChecked()== True:
            select_2 = 'Paypal'
            self.label_result.setText(f" libro seleccionado: {select_1}   Pago seleccionado: {select_2}")

        if self.radiobtn_card.isChecked()== True:
            select_2 = 'Credit Card'
            self.label_result.setText(f" libro seleccionado: {select_1}   Pago seleccionado: {select_2}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
